In [15]:
# sys things
import os
import sys
import json
import os

# networks
import requests

# data
import pandas as pd
import numpy as np
import scipy
import math
import seaborn as sns

In [16]:
import resources.utilities.utility_functions as ut

In [22]:
data, beaches, codes, geo, output=ut.make_local_paths()

In [23]:
print(data, beaches, codes, geo, output)

resources/surveydata resources/locationdata resources/mlwcodedefs resources/geodata output

In [27]:
j = pd.read_csv(data+'/OSPAR_ID_DutchEnglish.csv')
j[j.OSPAR_ID == 54]

                 ID Description    category  OSPAR_ID
60  textiel_kleding    Clothing  No plastic      54.0

In [32]:
f = pd.read_csv(data+'/mlw_codes.csv')
f[f.ospar_code == '54']

,code,material,description,source,source_two,source_three,parent_code,direct,single_use,micro,ospar_code
3,G135,Cloth,"Clothes, footware, headware, gloves",Clothing,Where does it come from,none,Parent code,True,False,False,54
5,G137,Cloth,"Clothing, towels & rags",Clothing,Where does it come from,none,Parent code,True,False,False,54

In [34]:
j[j.OSPAR_ID == 54]

array([1.000e+00, 2.000e+00, 3.000e+00, 4.100e+00, 4.200e+00, 4.300e+00,
       5.000e+00, 6.000e+00, 7.000e+00, 9.000e+00, 1.000e+01, 1.300e+01,
       1.400e+01, 1.500e+01, 1.600e+01, 2.000e+01, 2.100e+01, 2.400e+01,
       2.500e+01, 1.130e+02, 3.100e+01, 3.200e+01, 3.300e+01, 3.600e+01,
       3.800e+01, 4.000e+01, 4.200e+01, 4.300e+01, 4.400e+01, 1.171e+02,
       4.610e+01, 1.172e+02, 4.620e+01, 4.800e+01, 1.172e+03, 4.620e+02,
       6.100e+00, 4.710e+01, 4.720e+01, 2.210e+01, 1.900e+01, 4.720e+02,
       2.120e+02, 4.810e+02, 1.100e+01, 3.900e+01, 1.910e+01, 8.000e+00,
       2.100e+00, 1.700e+01, 3.500e+01, 4.310e+01, 2.220e+01, 3.810e+01,
       3.910e+01, 4.900e+01, 5.200e+01, 5.300e+01, 5.400e+01, 5.500e+01,
       5.700e+01, 5.900e+01, 6.000e+01, 6.100e+01, 6.300e+01, 6.400e+01,
       6.500e+01, 6.600e+01, 6.700e+01, 6.210e+01, 6.710e+01, 6.800e+01,
       6.900e+01, 7.200e+01, 7.300e+01, 7.400e+01, 7.500e+01, 8.100e+01,
       8.110e+01, 7.800e+01, 7.900e+01, 8.300e+01, 7.700e+01, 8.400e+01,
       8.800e+01, 7.600e+01, 8.600e+01, 8.000e+01, 8.200e+01, 1.200e+02,
       8.900e+01, 9.000e+01, 9.100e+01, 9.200e+01, 9.300e+01, 9.800e+01,
       9.820e+02, 1.022e+02, 9.700e+01, 9.900e+01, 1.800e+01, 1.000e+02,
       1.023e+02, 1.010e+02, 1.020e+02, 1.030e+02, 1.040e+02, 1.050e+02,
       1.172e+00])

In [41]:
j['rounded'] = j.OSPAR_ID.round(0)
j.rounded = j.rounded.astype('int')
somcode = j.rounded.unique()

In [42]:
a_key = [F"{x}" for x in somcode]
in_codes = f[f.ospar_code.isin(a_key)]
not_code = f[~f.ospar_code.isin(a_key)]
not_code

,code,material,description,source,source_two,source_three,parent_code,direct,single_use,micro,ospar_code
0,G212,Chemicals,Oil nodules or coal fragments -- not from a BBQ,Undefined,Where does it come from,none,Parent code,False,False,False,none
1,G213,Chemicals,Paraffin wax,Undefined,Where does it come from,none,Parent code,True,False,False,181
2,G214,Chemicals,Oil/tar,Construction,Where does it come from,none,Parent code,False,False,False,111
4,G136,Cloth,Shoes,Clothing,Where does it come from,none,Parent code,True,False,False,none
7,G139,Cloth,Backpacks,Utility items,Recreation,none,Parent code,True,False,False,none
...,...,...,...,...,...,...,...,...,...,...,...
255,G170,Wood,Wood (processed),Undefined,Where does it come from,NaN,Parent code,True,False,False,NaN
256,G171,Wood,Other wood < 50cm,Undefined,Where does it come from,NaN,Parent code,True,False,False,NaN
257,G172,Wood,Other wood > 50cm,Undefined,Where does it come from,NaN,Parent code,True,False,False,NaN
258,G173,Wood,Other,Undefined,Where does it come from,NaN,Parent code,True,False,False,NaN
259,G916,Wood,Pencils and pieces,Utility items,Where does it come from,none,G170,True,False,False,none

In [43]:
in_codes

,code,material,description,source,source_two,source_three,parent_code,direct,single_use,micro,ospar_code
3,G135,Cloth,"Clothes, footware, headware, gloves",Clothing,Where does it come from,none,Parent code,True,False,False,54
5,G137,Cloth,"Clothing, towels & rags",Clothing,Where does it come from,none,Parent code,True,False,False,54
6,G138,Cloth,Shoes and sandals,Clothing,Where does it come from,none,Parent code,True,False,False,57
9,G141,Cloth,Carpet,Utility items,Where does it come from,none,Parent code,False,False,False,55
12,G144,Cloth,Tampons,Personal hygiene,Water Treatment,none,Parent code,False,False,False,100
...,...,...,...,...,...,...,...,...,...,...,...
238,G133,Rubber,Condoms incl. packaging,Personal hygiene,Water Treatment,none,Parent code,True,True,False,97
240,G900,Rubber,Gloves latex personal protective equipment,Personal hygiene,Where does it come from,none,G134,True,True,False,53
242,G211,Unidentified,"Other medical items (swabs, bandaging, adhesiv...",Medical,Where does it come from,none,Parent code,True,True,False,105
246,G161,Wood,Processed timber,Packaging,Where does it come from,none,Parent code,False,False,False,69
250,G165,Wood,"Ice cream sticks, toothpicks, chopsticks",Packaging,Food and drink,none,Parent code,True,True,False,72

In [57]:
k = pd.read_csv(data+'/dataset_macrolitter_NL.csv')

In [58]:
k.columns

Index(['Unnamed: 0', 'Gebiedscode', 'Rivier', 'Coordinaten', 'Lat', 'Lon',
       'meting', 'date', 'doy', 'dop',
       ...
       'sanitair_tissues_wc_papier', 'sanitair_toiletverfrissers',
       'sanitair_overig_sanitair', 'medisch_verpakkingen', 'medisch_spuiten',
       'medisch_overig_medisch', 'Unnamed: 121', 'Totaal', 'Items/km',
       'granulaat_korrels'],
      dtype='object', length=125)

In [ ]:
def get_the_data(end_points):
    """Takes an array of 2d tuples or arrays ('name', 'url') and
    returns a dictionary of named data objects.

    Used in all notebooks that read or write data.
    """
    data = {}
    for pair in end_points:
        print(pair[1])
        data[pair[0]] = requests.get(pair[1])
    return data


def write_the_data(a_source, a_dir):
    """Writes the response objects (a JSON object) to the provided location.

    Used in notebooks that make an api call
    """
    outPut = []
    with open(a_dir, 'w') as outfile:
        json.dump(a_source.json(), outfile)

def put_the_data_to_local(end_points, here):
    """Gets the data from the provided URL and writes it to the provided location.

    Used in notebooks that make an api call
    """
    the_dict = get_the_data(end_points)
    write_the_data(the_dict, here)
    
def unpack_survey_results(survey_results):
    """Unpacks the surveys-results api-endpoint and adds the location name to each result dict.

    Used in notebooks that make an api call to 'https://mwshovel.pythonanywhere.com/api/surveys/daily-totals/code-totals/swiss/'
    """
    unpacked = []
    for location_data in survey_results:
        location = location_data['location']
        for each_dict in location_data['dailyTotals']:
            each_dict['location']=location
            unpacked.append(each_dict)
    return unpacked

In [69]:
a = requests.get('https://mwshovel.pythonanywhere.com/api/surveys/daily-totals/code-totals/swiss/')
x = a.json()
print(x[0]['location'])
n = pd.DataFrame(x[0]['dailyTotals'])
n['location']=x[0]['location']
print(x[1]['location'])
 = pd.DataFrame(x[1]['dailyTotals'])
n['location']=x[1]['location']
n

baby-plage-geneva

           date  code  pcs_m  quantity           location
0    2021-02-10  G178   0.01         1  baby-plage-geneva
1    2021-02-10  G211   0.03         3  baby-plage-geneva
2    2021-02-10   G30   0.03         3  baby-plage-geneva
3    2021-02-10   G79   0.04         4  baby-plage-geneva
4    2021-02-10  G113   0.04         4  baby-plage-geneva
..          ...   ...    ...       ...                ...
281  2019-01-16  G178   1.13        34  baby-plage-geneva
282  2019-01-16  G208   1.90        57  baby-plage-geneva
283  2019-01-16   G50   0.57        17  baby-plage-geneva
284  2019-01-16  G145   0.07         2  baby-plage-geneva
285  2019-01-16  G204   0.93        28  baby-plage-geneva

[286 rows x 5 columns]

In [61]:
k.columns

[x for x in k.columns]

['Unnamed: 0',
 'Gebiedscode',
 'Rivier',
 'Coordinaten',
 'Lat',
 'Lon',
 'meting',
 'date',
 'doy',
 'dop',
 'plastic_6_packringen',
 'plastic_tassen',
 'plastic_kleine_plastic_tasjes',
 'plastic_drankflessen_groterdan_halveliter',
 'plastic_drankflessen_kleinerdan_halveliter',
 'plastic_wikkels_van_drankflessen',
 'plastic_verpakking_van_schoonmaakmiddelen',
 'plastic_voedselverpakkingen_frietbakjes_etc',
 'plastic_cosmeticaverpakkingen',
 'plastic_motorolieverpakking_groterdan50cm',
 'plastic_jerrycans',
 'plastic_kratten',
 'plastic_auto_onderdelen',
 'plastic_doppen_en_deksels',
 'plastic_aanstekers',
 'plastic_speelgoed',
 'plastic_plastic_bekers_of_delen_daarvan',
 'plastic_netzakken',
 'plastic_handschoenen_huishoudelijk',
 'plastic_handschoenen_professioneel',
 'plastic_touw_diameter_groterdan_1cm',
 'plastic_touw_diameter_kleinerdan_1cm',
 'plastic_sportvisspullen',
 'plastic_breekstaafjes',
 'plastic_emmers',
 'plastic_industrieel_verpakkingsmateriaal',
 'plastic_helmen',
 'plastic_geweerpatronen',
 'plastic_schoenen',
 'plastic_plastic_stukjes_0_2_5cm_hard_plastic',
 'plastic_plastic_stukjes_2_5_50cm_hard_plastic',
 'plastic_plastic_stukjes_0_2_5cm_zacht_plastic',
 'plastic_plastic_stukjes_2_5_50cm_zacht_plastic',
 'plastic_overig_plastic',
 'plastic_piepschuim_0_2_5cm',
 'plastic_piepschuim_2_5_50cm',
 'plastic_piepschuim_voedselverpakkingen',
 'plastic_plastic_folies_groterdan_50cm',
 'plastic_hard_plastic_groterdan_50cm',
 'plastic_rietjes',
 'plastic_snoep_snack_chipsverpakking',
 'plastic_piepschuim_groterdan_50cm',
 'plastic_piepschuim_bekers',
 'plastic_bestek',
 'plastic_biofilm_waterfiltertjes',
 'plastic_kitspuiten',
 'plastic_kunststof_band_tiewraps',
 'plastic_lolliestokjes',
 'plastic_motorolieverpakking_kleinerdan50cm',
 'plastic_vuilniszakken',
 'plastic_schrijfwaren',
 'plastic_visdraad',
 'plastic_vuurwerk',
 'plastic_borden_new',
 'plastic_roerstaafjes_new',
 'plastic_bloempotten_new',
 'plastic_plakband_new',
 'rubber_ballonnen',
 'rubber_banden',
 'rubber_overig_rubber',
 'textiel_kleding',
 'textiel_vloerbedekking',
 'textiel_schoeisel',
 'textiel_overig_textiel',
 'papier_tassen',
 'papier_karton',
 'papier_sigarettenverpakking',
 'papier_sigarettenfilters',
 'papier_kartonnen_bekers',
 'papier_kranten',
 'papier_papier_overig',
 'papier_drankkarton',
 'papier_ondefinieerbaar',
 'hout_kurk',
 'hout_pellets',
 'hout_ijsstokjes',
 'hout_kwasten',
 'hout_overig_hout_keinderdan_50cm',
 'hout_overig_hout_groterdan_50cm',
 'metaal_aluminiumfolie',
 'metaal_capsules',
 'metaal_drankblikjes',
 'metaal_elektriciteitsdraad',
 'metaal_oud_ijzer',
 'metaal_kroonkurken',
 'metaal_oliedrum',
 'metaal_omheinigsdraad_prikkeldraad',
 'metaal_spuitbussen',
 'metaal_verfblik',
 'metaal_vislood',
 'metaal_voedselblikken',
 'metaal_wegwerpbarbecues',
 'metaal_overig_metaal_kleinerdan_50cm',
 'metaal_overig_metaal_groterdan_50cm',
 'glas_flessen_pottten',
 'glas_lampen_tl_lampen',
 'glas_overig_glas',
 'sanitair_cosmetica',
 'sanitair_plastic_wattenstaafjes',
 'sanitair_kartonnen_wattenstaafjes',
 'sanitair_vochtige_doekjes',
 'sanitair_condooms',
 'sanitair_maandverband_en_verpakkingen_ervan',
 'sanitair_plastic_kam_borstel',
 'sanitair_tampons_en_tamponapplicators',
 'sanitair_tissues_wc_papier',
 'sanitair_toiletverfrissers',
 'sanitair_overig_sanitair',
 'medisch_verpakkingen',
 'medisch_spuiten',
 'medisch_overig_medisch',
 'Unnamed: 121',
 'Totaal',
 'Items/km',
 'granulaat_korrels']

In [ ]:
def myfunc(descriptor):
    return osparcode


'plastic_6_packringen': myfunc('plastic_6_packringen')

In [60]:
k

,Unnamed: 0,Gebiedscode,Rivier,Coordinaten,Lat,Lon,meting,date,doy,dop,...,sanitair_tissues_wc_papier,sanitair_toiletverfrissers,sanitair_overig_sanitair,medisch_verpakkingen,medisch_spuiten,medisch_overig_medisch,Unnamed: 121,Totaal,Items/km,granulaat_korrels
0,0,W(078a)R-ZHNL,Waal,#REF!,51.8227,5.0159,0,20171021,294.0,293.0,...,NaN,0,2,0,0,0,NaN,170,1700,0
1,1,W(074b)R-REFE,Waal,#REF!,51.8290,5.0805,0,20171103,307.0,306.0,...,NaN,0,1,0,0,0,NaN,207,2070,0
2,2,W(062a)L-GENL,Waal,#REF!,51.8126,5.2358,0,20171016,289.0,288.0,...,NaN,0,1,0,0,0,NaN,214,2140,0
3,3,W(048a)L-GENL,Waal,#REF!,51.8475,5.4159,0,20171004,277.0,276.0,...,NaN,0,2,0,0,1,NaN,132,1320,0
4,4,W(046a)L-GENL,Waal,#REF!,51.8588,5.4222,0,20171002,275.0,274.0,...,NaN,0,1,0,0,0,NaN,46,460,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
386,403,M(005a)R-LINL,Maas,#REF!,50.8733,5.6906,3,20190228,59.0,788.0,...,1.0,2,3,10,5,0,NaN,3086,30860,113
387,404,M(004a)R-LINL,Maas,#REF!,50.7959,5.6953,3,20190310,69.0,798.0,...,0.0,1,7,1,2,1,NaN,832,8320,375
388,405,M(003a)R-LINL,Maas,#REF!,50.7823,5.7001,3,20190316,75.0,804.0,...,0.0,0,0,0,0,0,NaN,517,5170,0
389,406,M(002a)L-LIBE,Maas,#REF!,50.7810,5.6974,3,20190303,62.0,791.0,...,0.0,0,1,0,3,0,NaN,754,7540,50
390,407,M(001a)L-LIBE,Maas,#REF!,50.7554,5.6817,3,20190306,65.0,794.0,...,1.0,0,0,0,0,0,NaN,263,2630,0

In [63]:
k.groupby('Gebiedscode').date.nunique()

Gebiedscode
M 3 Heerewaarden    1
M(001a)L-LIBE       1
M(002a)L-LIBE       1
M(003a)R-LINL       2
M(004a)R-LINL       2
                   ..
W(090a)R-ZHNL       1
W(091a)R-ZHNL       1
W(092a)L-NBNL       2
W(093a)R-ZHNL       1
W4 Heerewaarden     1
Name: date, Length: 212, dtype: int64